### PR TITLE
Add / fixes api

### PR DESCRIPTION
**Pull request by nikkozp**

### CODE REVIEW

**Comment by JKorf** [comment]
this should target the alpha-futures branch I guess?

**Comment by nikkozp** [comment]
Hi. Yes, let it be in this version for now. There, binance started actively updating the API, we need to check everything and test it

**Comment by nikkozp** [comment]
Add these latest commits now, as there are hot fixes there

**Comment by JKorf** [comment]
Pushed a new version of alpha. I think we should try to get it to master shortly, as it is difficult to maintain both versions and I think most issues have been resolved by now?

**Comment by nikkozp** [comment]
I agree, based on issues on futures was errors, that need to check and fix

**Pull request merged**
