### PR TITLE
Made release builds deterministic

### PR DESCRIPTION
**Pull request by Kir-Antipov**
Hello there!
At the moment NuGet package has pretty bad health statistics:

current

The worst point is that the builds are not deterministic, so we, the users of the library, cannot be sure that the package obtained from NuGet was built from these sources and, as a result, doesn't contain any malicious code. Do we want to be sure that the library that has access to our finances doesn't contain malicious code? As for me the answer is: "Heck, yeah!"

To fix this issue, I've added few properties to the `.csproj` to make release builds deterministic. Also I've added `global.json` that indicates which SDK should be used during build process (I chose latest stable `5.0.103`, it can be obtained from [here](https://dotnet.microsoft.com/download/dotnet/5.0)).

Now we can check the commit that the build belongs to, then
```cmd
git clone https://github.com/JKorf/Binance.Net
cd Binance.Net
git checkout <commit-hash>
dotnet build -c Release
```
 and verify that the dll obtained from NuGet and dll that was built locally are binary identical.

Health statistics that describe the package built with this PR:

after this pr

### CODE REVIEW

**Comment by JKorf** [comment]
Thanks for the PR, looks good. I'm not an experienced Nuget publisher, so I was actually unaware of this. Thanks again!

**Comment by Kir-Antipov** [comment]
You're welcome!

> I'm not an experienced Nuget publisher, so I was actually unaware of this

Don't worry, this is not something that's *required* for every package, so a lot of us just don't know/don't bother ourselves with such details :)

P.S. - release builds now produce 2 packages: standard `.nupkg` and symbol package `.snupkg`, which should be also uploaded after the main package

**Comment by JKorf** [comment]
I've created a Release and pushed the symbols package successfully. To test it I created a new console app, and added the Bitfinex library from Nuget which I also added the symbols package for. Now when debugging I get this message: 
image

Is this expected?

**Comment by Kir-Antipov** [comment]
@JKorf, nope, since VS shouldn't try debug NuGet packages :)

Cannot reproduce.

VS version: `16.8.4`

"Just My Code" settings:

image


`.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bitfinex.Net" Version="3.4.1" />
  </ItemGroup>

</Project>
```

Program.cs:
```cs
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var client = new Bitfinex.Net.BitfinexClient();
            var summary = client.Get30DaySummary();
            Console.ReadKey();
        }
    }
}
```

Debug mode works as expected: no warnings at all and `step into` doesn't try to step into external code

**Comment by Kir-Antipov** [comment]
Debug output:

> 'ConsoleApp2.exe' (CoreCLR: clrhost): Loaded '\ConsoleApp2\bin\Debug\netcoreapp5.0\Bitfinex.Net.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.

If I disable "Just My Code", then I can accept downloading sources from GitHub and step into them. Without any warnings, again

**Comment by Kir-Antipov** [comment]
My assumptions about your case:

1) If something goes wrong, always blame cache! :) Try deleting bin/obj and `Clean`ing your solution
2) Maybe you somehow added reference not to the package, but to dll itself

It's problematic to come up with something else here, 'cause this is not how things should be, and there's nothing that can cause problems ¯\_(ツ)_/¯

Anyway, I just checked the package on three of my machines, and it's totally fine

**Comment by JKorf** [comment]
Hm weird, it's gone now. Must've been some caching issue. Thanks for the support on this :)

**Comment by Kir-Antipov** [comment]
Yup, it happens :) You're welcome)

**Pull request merged**
