### PR TITLE
Add milliseconds to KlineInterval enum

### PR DESCRIPTION
**Pull request by HypsyNZ**
https://github.com/JKorf/Binance.Net/issues/1057

### CODE REVIEW

**Comment by HypsyNZ** [comment]
This can be cherry picked

**Comment by JKorf** [comment]
I think it makes more sense to do this in either seconds (an SI unit), or minutes which is the smallest interval any exchange will offer. What do you think?

**Comment by JKorf** [comment]
I think it makes more sense to do this in either seconds (an SI unit), or minutes which is the smallest interval any exchange will offer. What do you think?

**Comment by HypsyNZ** [comment]
Updated to the most recent commit

**Comment by JKorf** [comment]
Changed this to seconds by the way. You cant specify a year in milliseconds without integer overflow ;)

**Comment by HypsyNZ** [comment]
Awesome, yeah I noticed one of the values was wrong too; so its for the best that you changed it.

**Pull request merged**
