### PR TITLE
added enums for base and trading pairs

### PR DESCRIPTION
**Pull request by confessore**
These additions allow the usage of reflection to enumerate over the various pairs supported by the exchange.

### CODE REVIEW

**Comment by kingchenc** [comment]
@confessore You missed alot of Base/Pairs

Missing Base: XRP, USDS
Missing Pairs: More then 70 Pairs

**Comment by confessore** [comment]
@kingchenc I will add those in. I was pulling the data from the client and overlooked them.
There are A TON of pairs to keep track of.

also, how do I get the travis ci checks to not fail?

**Comment by JKorf** [comment]
Hi, I'm wondering what you're trying to achieve with having these enums? If you want to itterate over the available trading pairs, couldn't you just use the data from GetExchangeInfo?

**Comment by confessore** [comment]
https://hastebin.com/vivofepewu.cs

this addition allows for enumeration of base/trading pairs with dynamic reflection without making an API call.

it works really well for the wpf application that I am working on.

also, I really don't see how GetExchangeInfo will show the trading pairs from the base pairs.

**Comment by confessore** [comment]
actually, I'll just add this to my own library rather than try to contribute
good luck out there

**Comment by nikkozp** [comment]
u can find all BasePair quiqly

var info = base.GetExchangeInfo();
string[] AllUniqueQuote = ExchangeInfo.Symbols.Select(x => x.QuoteAsset).Distinct().ToArray();

var allBTCPairs = ExchangeInfo.Symbols.Where(x=> x.QuoteAsset == "BTC").ToArray();
var allETHPairs = ExchangeInfo.Symbols.Where(x=> x.QuoteAsset == "ETH").ToArray();

**Pull request closed without merging**
