### PR TITLE
add missing OrderRespType on Spot

### PR DESCRIPTION
**Pull request by nikkozp**

### CODE REVIEW

**Comment by JKorf** [comment]
Is there a specific reason you want to set this?

**Comment by nikkozp** [comment]
> Set the response JSON. ACK, RESULT, or FULL; MARKET and LIMIT order types default to FULL, all other orders default to ACK.

For not `LIMIT `or `MARKET `order me need `FULL`, not `ACK`

**Comment by JKorf** [comment]
Fair enough, I'll just always set it fixed to Full, since the model is returned anyway. I don't think there is much benefit in setting it to anything other than Full.

**Comment by nikkozp** [comment]
I agree with you. But the documentation says that it may not return all the data, which means the model may be empty.

In any case, you need to have this parameter, because we do not know how the documentation may change in the future

**Comment by JKorf** [comment]
I've re-added the option in the latest version (was doing quite some work for Coin-M futures support anyway) so this PR is no longer needed.

**Pull request closed without merging**
